// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: sayhello.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BidirectionalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *BidirectionalRequest) Reset() {
	*x = BidirectionalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sayhello_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BidirectionalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidirectionalRequest) ProtoMessage() {}

func (x *BidirectionalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sayhello_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidirectionalRequest.ProtoReflect.Descriptor instead.
func (*BidirectionalRequest) Descriptor() ([]byte, []int) {
	return file_sayhello_proto_rawDescGZIP(), []int{0}
}

func (x *BidirectionalRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BidirectionalResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *BidirectionalResp) Reset() {
	*x = BidirectionalResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sayhello_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BidirectionalResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidirectionalResp) ProtoMessage() {}

func (x *BidirectionalResp) ProtoReflect() protoreflect.Message {
	mi := &file_sayhello_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidirectionalResp.ProtoReflect.Descriptor instead.
func (*BidirectionalResp) Descriptor() ([]byte, []int) {
	return file_sayhello_proto_rawDescGZIP(), []int{1}
}

func (x *BidirectionalResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_sayhello_proto protoreflect.FileDescriptor

var file_sayhello_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x61, 0x79, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x2a, 0x0a, 0x14, 0x42, 0x69, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2d, 0x0a, 0x11,
	0x42, 0x69, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x56, 0x0a, 0x0d, 0x42,
	0x69, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x12, 0x45, 0x0a, 0x12,
	0x42, 0x69, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x48, 0x65, 0x6c,
	0x6c, 0x6f, 0x12, 0x15, 0x2e, 0x42, 0x69, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x42, 0x69, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x28,
	0x01, 0x30, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sayhello_proto_rawDescOnce sync.Once
	file_sayhello_proto_rawDescData = file_sayhello_proto_rawDesc
)

func file_sayhello_proto_rawDescGZIP() []byte {
	file_sayhello_proto_rawDescOnce.Do(func() {
		file_sayhello_proto_rawDescData = protoimpl.X.CompressGZIP(file_sayhello_proto_rawDescData)
	})
	return file_sayhello_proto_rawDescData
}

var file_sayhello_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sayhello_proto_goTypes = []interface{}{
	(*BidirectionalRequest)(nil), // 0: BidirectionalRequest
	(*BidirectionalResp)(nil),    // 1: BidirectionalResp
}
var file_sayhello_proto_depIdxs = []int32{
	0, // 0: Bidirectional.BidirectionalHello:input_type -> BidirectionalRequest
	1, // 1: Bidirectional.BidirectionalHello:output_type -> BidirectionalResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sayhello_proto_init() }
func file_sayhello_proto_init() {
	if File_sayhello_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sayhello_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BidirectionalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sayhello_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BidirectionalResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sayhello_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sayhello_proto_goTypes,
		DependencyIndexes: file_sayhello_proto_depIdxs,
		MessageInfos:      file_sayhello_proto_msgTypes,
	}.Build()
	File_sayhello_proto = out.File
	file_sayhello_proto_rawDesc = nil
	file_sayhello_proto_goTypes = nil
	file_sayhello_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BidirectionalClient is the client API for Bidirectional service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BidirectionalClient interface {
	//一个BidirectionalHello的方法
	BidirectionalHello(ctx context.Context, opts ...grpc.CallOption) (Bidirectional_BidirectionalHelloClient, error)
}

type bidirectionalClient struct {
	cc grpc.ClientConnInterface
}

func NewBidirectionalClient(cc grpc.ClientConnInterface) BidirectionalClient {
	return &bidirectionalClient{cc}
}

func (c *bidirectionalClient) BidirectionalHello(ctx context.Context, opts ...grpc.CallOption) (Bidirectional_BidirectionalHelloClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Bidirectional_serviceDesc.Streams[0], "/Bidirectional/BidirectionalHello", opts...)
	if err != nil {
		return nil, err
	}
	x := &bidirectionalBidirectionalHelloClient{stream}
	return x, nil
}

type Bidirectional_BidirectionalHelloClient interface {
	Send(*BidirectionalRequest) error
	Recv() (*BidirectionalResp, error)
	grpc.ClientStream
}

type bidirectionalBidirectionalHelloClient struct {
	grpc.ClientStream
}

func (x *bidirectionalBidirectionalHelloClient) Send(m *BidirectionalRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *bidirectionalBidirectionalHelloClient) Recv() (*BidirectionalResp, error) {
	m := new(BidirectionalResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BidirectionalServer is the server API for Bidirectional service.
type BidirectionalServer interface {
	//一个BidirectionalHello的方法
	BidirectionalHello(Bidirectional_BidirectionalHelloServer) error
}

// UnimplementedBidirectionalServer can be embedded to have forward compatible implementations.
type UnimplementedBidirectionalServer struct {
}

func (*UnimplementedBidirectionalServer) BidirectionalHello(Bidirectional_BidirectionalHelloServer) error {
	return status.Errorf(codes.Unimplemented, "method BidirectionalHello not implemented")
}

func RegisterBidirectionalServer(s *grpc.Server, srv BidirectionalServer) {
	s.RegisterService(&_Bidirectional_serviceDesc, srv)
}

func _Bidirectional_BidirectionalHello_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BidirectionalServer).BidirectionalHello(&bidirectionalBidirectionalHelloServer{stream})
}

type Bidirectional_BidirectionalHelloServer interface {
	Send(*BidirectionalResp) error
	Recv() (*BidirectionalRequest, error)
	grpc.ServerStream
}

type bidirectionalBidirectionalHelloServer struct {
	grpc.ServerStream
}

func (x *bidirectionalBidirectionalHelloServer) Send(m *BidirectionalResp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *bidirectionalBidirectionalHelloServer) Recv() (*BidirectionalRequest, error) {
	m := new(BidirectionalRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Bidirectional_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Bidirectional",
	HandlerType: (*BidirectionalServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BidirectionalHello",
			Handler:       _Bidirectional_BidirectionalHello_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "sayhello.proto",
}
